# Tensors

In [6]:
import torch
import numpy as np
import matplotlib.pyplot as plt
#print(torch.__version__)

#scalar
scalar=torch.tensor(7)
print(scalar)
print(scalar.ndim)
print(scalar.item())# Get the Python number within a tensor (only works with one-element tensors)

# Vector
vector = torch.tensor([7, 7])
print(vector)
print(vector.ndim )# Check the number of dimensions of vector
print(vector.shape )# Check shape of vector

# Matrix
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
print(MATRIX)
print(MATRIX.ndim) # Check number of dimensions
print(MATRIX.shape)

# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
print(TENSOR)
print(TENSOR.ndim) # Check number of dimensions for TENSOR
print(TENSOR.shape) # Check shape of TENSOR
# it outputs torch.Size([1, 3, 3]).
#The dimensions go outer to inner.
#That means there's 1 dimension of 3 by 3.

# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
print(random_tensor)
print(random_tensor.dtype)

# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
print(random_image_size_tensor.shape)
print(random_image_size_tensor.ndim)

# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
print(zeros)
print(zeros.dtype)

# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
print(ones)
print(ones.dtype)

#Sometimes you might want a range of numbers, such as 1 to 10 or 0 to 100.
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
print(zero_to_ten)

# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
print(ten_zeros)


tensor(7)
0
7
tensor([7, 7])
1
torch.Size([2])
tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])
tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])
3
torch.Size([1, 3, 3])
tensor([[0.6060, 0.0941, 0.1691, 0.4783],
        [0.3388, 0.2963, 0.2402, 0.5690],
        [0.9602, 0.8189, 0.2040, 0.6620]])
torch.float32
torch.Size([224, 224, 3])
3
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.float32
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


# Datatype for tensors

In [7]:



#Note: tensor datatypes is one of the 3 big errors we can run into with pytorch and deeplearning:
 #1.Tensors not right datatype
 #2.Tensors not right shape
 #3.Tensors not on the  right device

 #Precision in computing wikipedia

# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, #can use "cuda", defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 
print(float_32_tensor.shape)
print(float_32_tensor.dtype)
print(float_32_tensor.device)

float_16_tensor2=float_32_tensor.type(torch.float16)
print(float_16_tensor2.dtype)

#Different datatype for tensor , CHECK FOR OTHER DATATYPES ON OFFICIAL WEBSITE TOO
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16) # torch.half would also work
print(float_16_tensor.dtype)

#one of tensors is torch.float32 and the other is torch.float16 (PyTorch often likes tensors to be the same format).
#Or one of your tensors is on the CPU and the other is on the GPU (PyTorch likes calculations between tensors to be on the same device).

# Create a tensor
# Find out details (or tensor attributes) about it
some_tensor = torch.rand(3, 4)
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Shape of tensor: {some_tensor.size()}")#gives same o/p as above
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

torch.Size([3])
torch.float32
cpu
torch.float16
torch.float16
tensor([[0.0938, 0.3629, 0.9576, 0.3273],
        [0.6843, 0.1713, 0.8480, 0.2957],
        [0.0247, 0.6244, 0.7712, 0.5228]])
Shape of tensor: torch.Size([3, 4])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# MANIPULATING TENSORS

In [9]:

# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10
# Multiply it by 10
tensor * 10
# Tensors don't change unless reassigned
tensor
# Subtract and reassign
tensor = tensor - 10
tensor
# Add and reassign
tensor = tensor + 10
tensor
# Can also use torch functions
torch.multiply(tensor, 10)
# Original tensor is still unchanged 
tensor


tensor([1, 2, 3])

# MATRIX MULTIPLICATION

In [10]:

# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

# Matrix multiplication
print(torch.matmul(tensor, tensor))
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
import time
start_time = time.time()
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)
end_time = time.time()
execution_time = end_time - start_time
print(f"Execution time: {execution_time} seconds")

start_time = time.time()
print(torch.matmul(tensor, tensor))#FASTER
end_time = time.time()
execution_time = end_time - start_time
print(f"Execution time: {execution_time} seconds")

# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

# torch.mm is a shortcut for matmul
print(torch.mm(tensor_A, tensor_B.T))



tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])
tensor(14)
tensor(14)
Execution time: 0.000518798828125 seconds
tensor(14)
Execution time: 0.0004420280456542969 seconds
Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])
tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])


# TENSOR AGGREGATION 

In [11]:

# Create a tensor
x = torch.arange(0, 100, 10)
print(x)
print(x.dtype)
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float32 datatype
print(f"Sum: {x.sum()}")
print(torch.max(x))
print(torch.min(x))
print(torch.mean(x.type(torch.float32)))
print(torch.sum(x))

#Positional min/max
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

#Change tensor datatype
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16
# Create a int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
torch.int64
Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450
tensor(90)
tensor(0)
tensor(45.)
tensor(450)
Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

# Reshaping, stacking, squeezing and unsqueezing

In [12]:

#torch.reshape(input, shape)	Reshapes input to shape (if compatible), can also use torch.Tensor.reshape().
#Tensor.view(shape)	            Returns a view of the original tensor in a different shape but shares the same data and memory as the original tensor.
#torch.stack(tensors, dim=0)	Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.
#torch.squeeze(input)	        Squeezes input to remove all the dimenions with value 1.
#torch.unsqueeze(input, dim)	Returns input with a dimension value of 1 added at dim.
#torch.permute(input, dims)	    Returns a view of the original input with its dimensions permuted (rearranged) to dims.

x = torch.arange(1., 8.)
x, x.shape
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape
# Changing z changes x
z[:, 0] = 5
z, x

# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked
x_stacked = torch.stack([x, x, x, x], dim=1) # try changing dim to dim=1 and see what happens
x_stacked
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])
Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])
Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


# Indexing (selecting data from tensors)

In [ ]:
# Create a tensor 
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

# Get index 0 of 0th and 1st dimension and all values of 2nd dimension 
x[0, 0, :] # same as x[0][0]

#  PyTorch tensors & NumPy
The two main methods you'll want to use for NumPy to PyTorch (and back again) are:

torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.
torch.Tensor.numpy() - PyTorch tensor -> NumPy array.

torch.Tensor.numpy() - PyTorch tensor -> NumPy array.

Note: By default, NumPy arrays are created with the datatype float64 and if you convert it to a PyTorch tensor, it'll keep the same datatype (as above).

However, many PyTorch calculations default to using float32.

So if you want to convert your NumPy array (float64) -> PyTorch tensor (float64) -> PyTorch tensor (float32), you can use 
             tensor = torch.from_numpy(array).type(torch.float32).

In [ ]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

# Change the array, keep the tensor
array = array + 1
array, tensor

# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

# Reproducibility (trying to take the random out of random)
How does this relate to neural networks and deep learning then?

We've discussed neural networks start with random numbers to describe patterns in data (these numbers are poor descriptions) and try to improve those random numbers using tensor operations (and a few other things we haven't discussed yet) to better describe patterns in data.

In short:

start with random numbers -> tensor operations -> try to make better (again and again and again)

Although randomness is nice and powerful, sometimes you'd like there to be a little less randomness.

Why?

So you can perform repeatable experiments.

In [ ]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

what if you wanted to created two random tensors with the same values.

As in, the tensors would still contain random values but they would be of the same flavour.

That's where torch.manual_seed(seed) comes in, where seed is an integer (like 42 but it could be anything) that flavours the randomness.

In [ ]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Resource: What we've just covered only scratches the surface of reproducibility in PyTorch. For more, on reproducbility in general and random seeds, I'd checkout:

    The PyTorch reproducibility documentation: (a good exericse would be to read through this for 10-minutes and even if you don't understand it now, being aware of it is important).

    The Wikipedia random seed page: (this'll give a good overview of random seeds and pseudorandomness in general).

# Running tensors on GPUs (and making faster computations)

In [14]:
!nvidia-smi

Tue May 21 10:02:02 2024       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.43.04    Driver Version: 515.43.04    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:1B:00.0 Off |                  N/A |
| 72%   77C    P2   257W / 350W |   6021MiB / 24576MiB |     51%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  Off  | 00000000:B2:00.0 Off |                  N/A |
| 74%   

In [15]:
# Check for GPU
import torch
torch.cuda.is_available()

True

In [16]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

cuda


In [17]:
# Count number of devices
torch.cuda.device_count()

3

#  Device-agnostic code 
##pytorch official website
Due to the structure of PyTorch, you may need to explicitly write device-agnostic (CPU or GPU) code; an example may be creating a new tensor as the initial hidden state of a recurrent neural network.

The first step is to determine whether the GPU should be used or not. A common pattern is to use Python’s argparse module to read in user arguments, and have a flag that can be used to disable CUDA, in combination with is_available(). In the following, args.device results in a torch.device object that can be used to move tensors to CPU or CUDA.

 CODE:-
        import argparse
        import torch

        parser = argparse.ArgumentParser(description='PyTorch Example')
        parser.add_argument('--disable-cuda', action='store_true',
                            help='Disable CUDA')
        args = parser.parse_args()
        args.device = None
        if not args.disable_cuda and torch.cuda.is_available():
            args.device = torch.device('cuda')
        else:
            args.device = torch.device('cpu')

USAGE:-

Now that we have args.device, we can use it to create a Tensor on the desired device.

        x = torch.empty((8, 42), device=args.device)
        net = Network().to(device=args.device)

# Putting tensors (and models) on the GPU

Note: Putting a tensor on GPU using to(device) (e.g. some_tensor.to(device)) returns a copy of that tensor, e.g. the same tensor will be on CPU and GPU. To overwrite tensors, reassign them:

some_tensor = some_tensor.to(device)

In [ ]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

# Moving tensors back to the CPU

If tensor is on GPU, can't transform it to NumPy (this will error)
    tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

#The above returns a copy of the GPU tensor in CPU memory so the original tensor is still on GPU.
tensor_on_gpu